### ISSUE TITLE
Fix "cd" command under setup in CONTRIBUTING.md

### ISSUE THREAD

**Issue by SamarthRanjanRay** [zapify-ui/zapify#77]
**Fix CONTRIBUTING.md**
Below the setup heading, the 3rd list item tells the user to change directory into zapify-ui, but when the git is cloned, it actually creates the directory by the name of the repository "zapify"

**To Reproduce**
So fixing that single line of code "cd zapify-ui" to "cd zapify" would be better

**Expected behavior**
The user with very less experience in git wouldn't find any error or difficulty in setting up this repository's clone.

**Comment by piyush97** [comment]
Resolved! 
Thanks @SamarthRanjanRay
