### ISSUE TITLE
[easy task] CSS Doesn't load in Production: NPM build  

### ISSUE THREAD

**Issue by piyush97** [zapify-ui/zapify#78]
**Describe the bug**
Styles don't load in Production

**Expected behavior**
Styles to get loaded

**Screenshots**
without CSS/Styling (Current condition)
![image](https://user-images.githubusercontent.com/18229627/63879020-683dff80-c9e8-11e9-9aaa-8dbb862e2862.png)
With CSS (Required)
![image](https://user-images.githubusercontent.com/18229627/63879109-9f141580-c9e8-11e9-8dbc-5bf9d89f7e6a.png)

# Please Help

**Comment by pniedzwiedzinski** [comment]
I would like to do this

**Comment by piyush97** [comment]
Sure, please do it @pniedzwiedzinski

**Comment by pniedzwiedzinski** [comment]
I can not reproduce the problem :/

Am I doing something wrong:
- `npm run build-css`
- `npm run build`
- `npm run storybook`

**Comment by piyush97** [comment]
@pniedzwiedzinski 
The Problem is, if I'm using any component of zapify-ui in  a create-react-app or any react app.

by using import component from "componentpath";

it's loading the component but not the styling for the particular component.

**Comment by piyush97** [comment]
@pniedzwiedzinski status?

**Comment by pniedzwiedzinski** [comment]
Sory but I can't do it right now 😢
