### ISSUE TITLE
[Easy Task][HacktoberFest] CSS Doesn't load on npm build

### ISSUE THREAD

**Issue by piyush97** [zapify-ui/zapify#81]
**Describe the bug**
Styles don't load in Production

**Expected behavior**
Styles to get loaded

**Screenshots**
without CSS/Styling (Current condition)
![image](https://user-images.githubusercontent.com/18229627/63879020-683dff80-c9e8-11e9-9aaa-8dbb862e2862.png)
With CSS (Required)
![image](https://user-images.githubusercontent.com/18229627/63879109-9f141580-c9e8-11e9-8dbc-5bf9d89f7e6a.png)

# Please Help

**Comment by lawrence-dass** [comment]
Can I take work on this please?

**Comment by piyush97** [comment]
@Lawrence4code Sure. Please try to do this ASAP.
